# Generated by Django 5.0.1 on 2024-01-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerpost',
            name='content',
        ),
        migrations.AddField(
            model_name='farmerpost',
            name='farm_name',
            field=models.CharField(default='Default Farm', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerpost',
            name='image',
            field=models.ImageField(default='path/to/default-image.jpg', upload_to='farmer_posts/'),
        ),
        migrations.AddField(
            model_name='farmerpost',
            name='quantity',
            field=models.CharField(default='Default Quantity', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmerpost',
            name='location',
            field=models.CharField(default='Default Price', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmerpost',
            name='price',
            field=models.CharField(default='Default Price', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmerpost',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
