# Generated by Django 5.0.1 on 2024-01-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
