# Generated by Django 5.0.1 on 2024-01-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
